server:
  port: 8002

spring:
  application:
    name: content-service
  cloud:
    nacos:
      discovery:
        server-addr: 106.54.198.101:8848
  datasource:
    url: jdbc:mysql://106.54.198.101:3306/ksf?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: ksf123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: content-service-pool
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl